import Head from 'next/head'
import MenuMobile from '../components/MenuMobile/Menu'
import PageContainer from "../components/PageContainer"
import AmbicionesLayout from '../components/sobreMi/AmbicionesLayout'
import BotJs from '../components/sobreMi/BotJs'
import HobbiesLayout from '../components/sobreMi/HobbiesLayout'
import MenuSobreMi from '../components/sobreMi/MenuSobreMi'
import SobreMiTitle from '../components/sobreMi/SobreMiTitle'
import PersonalidadLayout from '../components/sobreMi/PersonalidadLayout'
import SobreMiContainer from '../components/sobreMi/SobreMiContainer'
import StudiesLayout from '../components/sobreMi/StudiesLayout'
import { DataProvider } from '../context/dataContext'

const sobremi = ()=>{
    return(
        <>
            <DataProvider>

                <Head>
                    <title>Webs</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>

                <PageContainer>
                    <SobreMiContainer>

                        <SobreMiTitle />
                        <MenuSobreMi />
                        <BotJs />
                        <StudiesLayout />
                        <PersonalidadLayout />
                        <HobbiesLayout />
                        <AmbicionesLayout />

                    </SobreMiContainer>
                    <MenuMobile />
                </PageContainer>
            </DataProvider>
            
        </>
    )
}

export default sobremi